driver:
  name: vagrant
  driver-config:
    use_cachier_plugin: true
provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
suites:
  - name: weblogic-server-10-3-6
    run_list:
      - recipe[weblogic-server-10-3-6]
    attributes:
          common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
  - name: weblogic-server-12-1-1
    run_list:
      - recipe[weblogic-server-12-1-1]
    attributes:
          common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
  - name: weblogic-server-12-1-2
    run_list:
      - recipe[weblogic-server-12-1-2]
    attributes:
          common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
  - name: weblogic-server-12-1-3
    run_list:
      - recipe[weblogic-server-12-1-3]
    attributes:
          common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
  - name: weblogic-server-multi
    run_list:
      - recipe[weblogic-server-multi]
    attributes:
          common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
  - name: weblogic-server-usr
    run_list:
      - recipe[weblogic-server-usr]
    attributes:
          common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
